# Generated by Django 4.1 on 2022-12-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devolu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='costodolar',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
