# Generated by Django 4.1 on 2022-12-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devolu', '0002_devolucion_costodolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='costo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
